# Generated by Django 3.0.6 on 2020-06-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20200609_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_namme',
            new_name='product_name',
        ),
    ]
