# Generated by Django 3.0.6 on 2020-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20200609_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_email', models.CharField(max_length=50)),
                ('sender_phone', models.CharField(max_length=50)),
                ('msg_desc', models.CharField(max_length=2000)),
            ],
        ),
    ]
