# Generated by Django 3.0.6 on 2020-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg_desc',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender_phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
